app: nil

server:
  ip: 0.0.0.0
  port: 44666
  debug: true
  https:
    enable: false
    port: 443
    redirect-to: https://localhost
    server-name: localhost
    cert: ./dist/cert.pem
    key: ./dist/key.pem
  static-site:
    serve: true
    index: index.html
    resources: dist/static/
    envjs: |
      window.snenv={
        "web":{
          "domain":"http://localhost:444",
          "storage_path":"http://localhost:322/api"
        }
      }

web:
  domain: localhost
  cors-host: "http://localhost:44666"
  path-prefix: /api
