app: nil

server:
  ip: 0.0.0.0
  port: 44666
  debug: true
  static-site:
    serve: true
    index: index.html
    resources: built/static/

web:
  domain: localhost
  cors-host: "http://localhost:44666"
  path-prefix: /api
