server:
  ip:        0.0.0.0
  port:      44666
  verbosity: debug
  https:
    enable:          false
    port:            443
    cert:            ./dist/cert.pem
    key:             ./dist/key.pem
    server-name:     localhost
    enable-redirect: true
    redirect-to:     https://localhost

web-api:
  domain:      localhost
  cors-host:   "https://localhost"
  path-prefix: /api

static-site:
  serve:     true
  index:     index.html
  resources: ./dist/static
  envjs:     |
             window.snenv={
               "web":{
                 "domain":"http://localhost:44666",
                 "storage_path":"http://localhost:44666/api"
               }
             }
