app: nil

server:
  ip: 0.0.0.0
  port: 44666
  debug: true
  static-site:
    serve: true
    index: index.html
    resources: dist/static/
    envjs: |
      window.snenv={
        "web":{
          "domain":"http://localhost:444",
          "storage_path":"http://localhost:322/api"
        }
      }

web:
  domain: localhost
  cors-host: "http://localhost:44666"
  path-prefix: /api
