app: nil

server:
  ip: 0.0.0.0
  port: 3333
  debug: true
  static-site:
    serve: true
    index: index.html
    resources: react/

web:
  domain: localhost
  cors-host: "http://localhost:3333"
  path-prefix: /api
