version: '3.7'

services:
    node:
        image: node:latest
        container_name: sn-react
        volumes:
            - ./:/project
            - ./../../dist/static:/project/build
        working_dir: /project
        userns_mode: host
        ports:
            - 3000:3000
        tty: true
